// Generated by CoffeeScript 1.6.3
(function() {
  var CSRange, CSSingleTextLineRange, CSTextRange, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  CSRange = (function() {
    function CSRange(location, length) {
      this.location = location != null ? location : 0;
      this.length = length != null ? length : 0;
    }

    CSRange.prototype.maxEdge = function() {
      return this.location + this.length;
    };

    return CSRange;

  })();

  CSTextRange = (function(_super) {
    __extends(CSTextRange, _super);

    function CSTextRange(location, length, lines) {
      this.location = location != null ? location : 0;
      this.length = length != null ? length : 0;
      this.lines = lines != null ? lines : [];
    }

    return CSTextRange;

  })(CSRange);

  CSSingleTextLineRange = (function(_super) {
    __extends(CSSingleTextLineRange, _super);

    function CSSingleTextLineRange(location, length, lineNumber) {
      this.location = location != null ? location : 0;
      this.length = length != null ? length : 0;
      this.lineNumber = lineNumber != null ? lineNumber : 0;
    }

    return CSSingleTextLineRange;

  })(CSRange);

  root.CSRange = CSRange;

  root.CSTextRange = CSTextRange;

  root.CSSingleTextLineRange = CSSingleTextLineRange;

}).call(this);
