// Generated by CoffeeScript 1.6.3
(function() {
  var NSAttributedRange, NSRange, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  NSRange = (function() {
    function NSRange(location, length) {
      this.location = location != null ? location : 0;
      this.length = length != null ? length : 0;
    }

    NSRange.prototype.maxEdge = function() {
      return this.location + this.length;
    };

    return NSRange;

  })();

  NSAttributedRange = (function(_super) {
    __extends(NSAttributedRange, _super);

    function NSAttributedRange(location, length, attributes) {
      this.location = location != null ? location : 0;
      this.length = length != null ? length : 0;
      this.attributes = attributes != null ? attributes : {};
    }

    return NSAttributedRange;

  })(NSRange);

  root.NSRange = NSRange;

  root.NSAttributedRange = NSAttributedRange;

}).call(this);
