// Generated by CoffeeScript 1.6.3
(function() {
  var NSAttributedRange, NSRange, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  NSRange = (function() {
    function NSRange(location, length) {
      this.location = location;
      this.length = length;
    }

    return NSRange;

  })();

  NSAttributedRange = (function(_super) {
    __extends(NSAttributedRange, _super);

    function NSAttributedRange(location, length, attributes) {
      this.location = location;
      this.length = length;
      this.attributes = attributes != null ? attributes : {};
    }

    return NSAttributedRange;

  })(NSRange);

}).call(this);
